version: "3.9"

services:
  database:
    image: mysql
    container_name: ping-database
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - dev-ping:/var/lib/mysql
    networks:
      - ping-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234565418848468468248624682ddd
      - MYSQL_USER=monitoruser
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=pingdom
  node:
    build:
      context: .
      dockerfile: "Dockerfile"
    restart: unless-stopped
    working_dir: /home/app
    env_file: ./.env
    depends_on:
      - database
      - redis
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=database
      - REDIS_HOST=redis
    volumes:
      - ./:/home/app
    networks:
      - ping-net
    ports:
      - 3000:3000
    command: "npm run dev"
    #  -"npm rebuild bcrypt --build-from-source"
  redis:
    image: redis:7.0-rc1-alpine
    container_name: ping-cache
    restart: unless-stopped
    networks:
      - ping-net
    volumes:
      - dev-ping:/var/lib/redis
    ports:
      - 6379:6379

networks:
  ping-net:
volumes:
  dev-ping:
