version: "3.9"

services:
  database:
    image: mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - dev-ping:/var/lib/mysql
    networks:
      - ping-net
    environment:
      MYSQL_USER: "pinguser"
      MYSQL_DATABASE: "pingdom"
      MYSQL_ROOT_PASSWORD: "123456"
      # PRODUCTION: development
  node:
    image: "node:latest"
    #image: "node-ping"
    user: "node"
    restart: unless-stopped
    working_dir: /home/app
    depends_on:
      - database
    environment:
      - NODE_ENV=development
      - ./.env
      - DATABASE_HOST=database
    volumes:
      - ./:/home/app
    networks:
      - ping-net
    ports:
      - 3000:3000
    command: " npm run dev"
    #  -"npm rebuild bcrypt --build-from-source"
  redis:
    image: "redis:latest"
    restart: unless-stopped
    networks:
      - ping-net
    volumes:
      - dev-ping:/var/lib/redis
    ports:
      - 6379:6379

networks:
  ping-net:
    driver: bridge
volumes:
  dev-ping:
